on:
  # Runs on pushes targeting the prod branch
  push:
    branches: ["prod"]

name: Publish Website
jobs:
    web-deploy:
        name: publish
        runs-on: ubuntu-latest
        environment: prod
        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: sftp
              uses: AbleLincoln/push-to-sftp@v1.0
              with:
                  host: ${{ vars.HOSTNAME }}
                  port: 22
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  sourceDir: ./
                  targetDir: ./
